# **Comprehensive Sales Transactions Database**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving archive (2).zip to archive (2) (1).zip

In [ ]:
#Load Data
import pandas as pd
import numpy as np

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("✅ Data Loaded Successfully\n")
print("Shape of dataset:", df.shape)
print("\n🔹 First 5 Rows:")
display(df.head())

✅ Data Loaded Successfully

Shape of dataset: (1194, 12)

🔹 First 5 Rows:

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [ ]:
#Data Info
print("📊 Data Info:")
df.info()

print("\n📊 Summary Statistics:")
display(df.describe(include='all'))

📊 Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1194 non-null   object
 1   Amount        1194 non-null   int64
 2   Profit        1194 non-null   int64
 3   Quantity      1194 non-null   int64
 4   Category      1194 non-null   object
 5   Sub-Category  1194 non-null   object
 6   PaymentMode   1194 non-null   object
 7   Order Date    1194 non-null   object
 8   CustomerName  1194 non-null   object
 9   State         1194 non-null   object
 10  City          1194 non-null   object
 11  Year-Month    1194 non-null   object
dtypes: int64(3), object(9)
memory usage: 112.1+ KB

📊 Summary Statistics:

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
count,1194,1194.000000,1194.000000,1194.000000,1194,1194,1194,1194,1194,1194,1194,1194
unique,547,NaN,NaN,NaN,3,12,5,648,802,6,18,61
top,B-26032,NaN,NaN,NaN,Furniture,Tables,Debit Card,2022-12-08,Jacqueline Harris,New York,Buffalo,2022-12
freq,12,NaN,NaN,NaN,407,122,260,8,4,226,90,45
mean,NaN,5178.089615,1348.992462,10.674204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2804.921955,1117.992573,5.777102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,508.000000,50.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2799.000000,410.000000,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,5152.000000,1014.000000,11.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,7626.000000,2035.000000,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,9992.000000,4930.000000,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Column Names
print("📌 Column Names:")
for col in df.columns:
    print("-", col)

📌 Column Names:
- Order ID
- Amount
- Profit
- Quantity
- Category
- Sub-Category
- PaymentMode
- Order Date
- CustomerName
- State
- City
- Year-Month

In [ ]:
#Data Dictionary
data_dict = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.astype(str)
})

print("📘 Data Dictionary:")
display(data_dict)

data_dict.to_csv("data_dictionary.csv", index=False)

📘 Data Dictionary:

               Column Name Data Type
Order ID          Order ID    object
Amount              Amount     int64
Profit              Profit     int64
Quantity          Quantity     int64
Category          Category    object
Sub-Category  Sub-Category    object
PaymentMode    PaymentMode    object
Order Date      Order Date    object
CustomerName  CustomerName    object
State                State    object
City                  City    object
Year-Month      Year-Month    object

In [ ]:
#Missing Values
print("🔍 Missing Values in Each Column:")
missing = df.isnull().sum()
display(missing)

🔍 Missing Values in Each Column:

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
Year-Month      0
dtype: int64

In [ ]:
#Duplicate Check
duplicates = df.duplicated().sum()
print("🔁 Number of Duplicate Rows:", duplicates)

🔁 Number of Duplicate Rows: 0

In [ ]:
#Remove Duplicates
df = df.drop_duplicates()

print("✅ After Removing Duplicates:")
print("New Shape:", df.shape)

✅ After Removing Duplicates:
New Shape: (1194, 12)

In [ ]:
#Handle Missing Values
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna("Unknown")
    else:
        df[col] = df[col].fillna(df[col].median())

print("✅ Missing Values After Cleaning:")
display(df.isnull().sum())

✅ Missing Values After Cleaning:

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
Year-Month      0
dtype: int64

In [ ]:
#Convert Date Columns
for col in df.columns:
    if "date" in col.lower() or "dob" in col.lower():
        df[col] = pd.to_datetime(df[col], errors='coerce')

print("📅 Data Types After Date Conversion:")
print(df.dtypes)

📅 Data Types After Date Conversion:
Order ID                object
Amount                   int64
Profit                   int64
Quantity                 int64
Category                object
Sub-Category            object
PaymentMode             object
Order Date      datetime64[ns]
CustomerName            object
State                   object
City                    object
Year-Month              object
dtype: object

In [ ]:
#Feature Engineering
today = pd.Timestamp.today()

# Create Age if DOB exists
if 'dob' in df.columns:
    df['customer_age'] = (today - df['dob']).dt.days // 365
    print("✅ Customer Age Column Created")

# Extract Month from Purchase Date
for col in df.columns:
    if "purchase" in col.lower() and "date" in col.lower():
        df['purchase_month'] = df[col].dt.month
        print("✅ Purchase Month Column Created")

print("\n🔹 Updated Data:")
display(df.head())

🔹 Updated Data:

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [ ]:
#Outlier Detection & Removal
numeric_cols = df.select_dtypes(include=np.number).columns

print("📊 Numeric Columns:", list(numeric_cols))

for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    before = df.shape[0]

    df = df[(df[col] >= q1 - 1.5 * iqr) &
            (df[col] <= q3 + 1.5 * iqr)]

    after = df.shape[0]

    print(f"🔧 {col}: Removed {before - after} outliers")

📊 Numeric Columns: ['Amount', 'Profit', 'Quantity']
🔧 Amount: Removed 0 outliers
🔧 Profit: Removed 10 outliers
🔧 Quantity: Removed 0 outliers

In [ ]:
#Final Dataset Check
print("✅ Final Cleaned Dataset Shape:", df.shape)

print("\n🔹 Final Preview:")
display(df.head())

print("\n🔹 Final Info:")
df.info()

✅ Final Cleaned Dataset Shape: (1184, 12)

🔹 Final Preview:

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

🔹 Final Info:
<class 'pandas.core.frame.DataFrame'>
Index: 1184 entries, 0 to 1193
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1184 non-null   object
 1   Amount        1184 non-null   int64
 2   Profit        1184 non-null   int64
 3   Quantity      1184 non-null   int64
 4   Category      1184 non-null   object
 5   Sub-Category  1184 non-null   object
 6   PaymentMode   1184 non-null   object
 7   Order Date    1184 non-null   datetime64[ns]
 8   CustomerName  1184 non-null   object
 9   State         1184 non-null   object
 10  City          1184 non-null   object
 11  Year-Month    1184 non-null   object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 120.2+ KB

In [ ]:
#Save & Download Files
df.to_csv("cleaned_data.csv", index=False)

from google.colab import files
files.download("cleaned_data.csv")
files.download("data_dictionary.csv")

print("📁 Files downloaded successfully!")

📁 Files downloaded successfully!